name: Run My Bash Script

on:
  workflow_dispatch:

jobs:
  bash-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x m.sh

      - name: Run your script
        run: ./m.sh
